### ISSUE TITLE
refactor home learning page

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-portal-frontend#6]
Refactor home learning page to use the new form and page components

**Comment by lauracumming** [comment]
https://www.figma.com/design/9pMg7hFzK5YkjcnmwZsFl1/Portal-UI?node-id=0-6834&m=dev&t=dKoDra7oneYZzPLn-1

**Comment by lauracumming** [comment]
![Image](https://github.com/user-attachments/assets/0dc9b758-713c-4fec-9b20-897cac14dec8)

**Comment by SKairinos** [comment]
made the copy changes

**Comment by SKairinos** [comment]
@lauracumming , can you please share the links we should point to for all the buttons
 on [this page](https://www.codeforlife.education/home-learning)?
